# -*- coding: utf-8 -*-
"""Final_DSML_Code_Evans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRnEe6NZJ5O56BtPcHKeTE_O93gIpUdd
"""

# ============================================
# Soli Evans - Final Project
# Predicting Short-Term Absence Risk in NBA Players
# ============================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

# -----------------------------
# 1. LOAD DATA
# -----------------------------
df = pd.read_csv("database_24_25.csv")

# -----------------------------
# 2. RENAME COLUMNS
# -----------------------------
df = df.rename(columns={
    "Player": "player_name",
    "Tm": "team",
    "Opp": "opponent",
    "Res": "result",
    "MP": "minutes_played",
    "FGA": "fg_attempts",
    "FG%": "fg_pct",
    "3PA": "three_pt_attempts",
    "3P%": "three_pt_pct",
    "FTA": "ft_attempts",
    "FT%": "ft_pct",
    "ORB": "off_rebounds",
    "DRB": "def_rebounds",
    "TRB": "rebounds",
    "AST": "assists",
    "STL": "steals",
    "BLK": "blocks",
    "TOV": "turnovers",
    "PF": "personal_fouls",
    "PTS": "points",
    "GmSc": "game_score",
    "Data": "game_date"
})

# -----------------------------
# 3. CLEAN DATA
# -----------------------------
df["game_date"] = pd.to_datetime(df["game_date"], errors="coerce")
df = df.dropna(subset=["player_name", "team", "game_date"])

numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.drop_duplicates()

# -----------------------------
# 4. SORT
# -----------------------------
df = df.sort_values(["player_name", "game_date"]).reset_index(drop=True)

# -----------------------------
# 5. FEATURE ENGINEERING
# -----------------------------
df["prev_game_date"] = df.groupby("player_name")["game_date"].shift(1)
df["days_since_last_game"] = (df["game_date"] - df["prev_game_date"]).dt.days

group = df.groupby("player_name")

df["minutes_last_3"] = group["minutes_played"].transform(lambda x: x.shift(1).rolling(3, min_periods=1).sum())
df["minutes_last_5"] = group["minutes_played"].transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
df["avg_minutes_last_3"] = group["minutes_played"].transform(lambda x: x.shift(1).rolling(3, min_periods=1).mean())

df["back_to_back"] = np.where(df["days_since_last_game"] == 1, 1, 0)

def rest_cat(x):
    if pd.isna(x): return "unknown"
    if x <= 1: return "low_rest"
    elif x == 2: return "medium_rest"
    else: return "high_rest"

df["rest_category"] = df["days_since_last_game"].apply(rest_cat)

# -----------------------------
# 6. TEAM SCHEDULE
# -----------------------------
team_sched = df[["team", "game_date"]].drop_duplicates().sort_values(["team", "game_date"])
team_sched["next_team_game"] = team_sched.groupby("team")["game_date"].shift(-1)

df = df.merge(team_sched, on=["team", "game_date"], how="left")

# -----------------------------
# 7. TARGET VARIABLE
# -----------------------------
df["next_player_game"] = df.groupby("player_name")["game_date"].shift(-1)

df["missed_next_game"] = np.where(
    df["next_team_game"].isna(),
    np.nan,
    np.where(df["next_player_game"] == df["next_team_game"], 0, 1)
)

df = df.dropna(subset=["missed_next_game"])
df["missed_next_game"] = df["missed_next_game"].astype(int)

# -----------------------------
# 8. MODEL DATA
# -----------------------------
features_num = [
    "minutes_played", "points", "assists", "rebounds",
    "steals", "blocks", "turnovers", "game_score",
    "days_since_last_game", "minutes_last_3", "minutes_last_5",
    "avg_minutes_last_3", "back_to_back"
]

features_cat = ["team", "opponent", "rest_category"]

X = df[features_num + features_cat]
y = df["missed_next_game"]

# -----------------------------
# 9. TRAIN TEST SPLIT
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# 10. PREPROCESSING
# -----------------------------
num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", num_pipe, features_num),
    ("cat", cat_pipe, features_cat)
])

# -----------------------------
# 11. LOGISTIC REGRESSION
# -----------------------------
log_model = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

log_model.fit(X_train, y_train)
pred = log_model.predict(X_test)
prob = log_model.predict_proba(X_test)[:,1]

print("\nLOGISTIC REGRESSION")
print(classification_report(y_test, pred))
print("ROC AUC:", roc_auc_score(y_test, prob))

# -----------------------------
# 12. RANDOM FOREST
# -----------------------------
rf_model = Pipeline([
    ("prep", preprocess),
    ("model", RandomForestClassifier(n_estimators=200, random_state=42))
])

rf_model.fit(X_train, y_train)
pred_rf = rf_model.predict(X_test)
prob_rf = rf_model.predict_proba(X_test)[:,1]

print("\nRANDOM FOREST")
print(classification_report(y_test, pred_rf))
print("ROC AUC:", roc_auc_score(y_test, prob_rf))

# -----------------------------
# 13. SAVE OUTPUT
# -----------------------------
df.to_csv("final_dataset.csv", index=False)

print("\nDone. Dataset saved.")